on:
  push:
    branches:
      - main

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export game
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4
    - name: export
      uses: firebelley/godot-export@v2.8.0
      with:
        base_version: 0.4.0
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.3/Godot_v3.3-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.3/Godot_v3.3-stable_export_templates.tpz
        godot_template_version: 3.3.stable
        relative_project_path: ./
      env:
        GITHUB_TOKEN: ${{ secrets.EXPORT_GITHUB_TOKEN }}