on:
  release:
    types: [created, edited]

jobs:
  release_html:
    runs-on: ubuntu-latest
    steps:
      - name: Download html
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: HTML.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Release HTML
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_SECRET }}
          CHANNEL: html5
          ITCH_GAME: Breakout
          ITCH_USER: Samich
          PACKAGE: HTML.zip
  release_mac:
    runs-on: ubuntu-latest
    steps:
      - name: Download mac
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: Mac.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Release Mac
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_SECRET }}
          CHANNEL: mac
          ITCH_GAME: Breakout
          ITCH_USER: Samich
          PACKAGE: Mac.zip
  release_windows:
    runs-on: ubuntu-latest
    steps:
      - name: Download windows
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: Windows.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Release Windows
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_SECRET }}
          CHANNEL: windows
          ITCH_GAME: Breakout
          ITCH_USER: Samich
          PACKAGE: Windows.zip